---
title: "Single cpg meta analysis in male"
author: "Lanyu Zhang, Tiago C. Silva, Lily Wang"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    theme: lumen
    highlight: kate
    toc: true
    number_sections: true
    df_print: paged
    code_download: true
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data retrival

```{R, message = FALSE, warning = FALSE, results = 'hide'}
library(dplyr)
```

```{R}
data.dir <- "../meta_analysis_single_cpg_results/"
data.gasparoni <- "../DATASETS/GASPARONI/step8_single_cpg_pval/"
data.london <- "../DATASETS/LONDON/step7_single_cpg_pval/"
data.mtsinai <- "../DATASETS/MtSinai/step7_single_cpg_pval/"
data.rosmap <- "../DATASETS/ROSMAP/step8_single_cpg_pval/"
data.annot <- "../../coMethDMR_metaAnalysis/DATA_annotations/"
for(p in grep("dir",ls(),value = T)) dir.create(get(p),recursive = TRUE,showWarnings = FALSE)
```

# Create merged datasets for meta analysis

```{R, include = FALSE}
load(paste0(data.gasparoni, "/GASPARONI_single_cpg.rda"))
load(paste0(data.london, "/LONDON_single_cpg.rda"))
load(paste0(data.mtsinai, "/MtSinai_single_cpg.rda"))
load(paste0(data.rosmap, "/ROSMAP_single_cpg.rda"))
```

## for all

```{R}
cohort_ls <- list(
  Gasparoni = gasparoni_all_stageSexM_linear_df,
  London = london_all_stageSexM_linear_df,
  MtSinai = mtsinai_all_stageSexM_linear_df,
  ROSMAP = rosmap_all_stageSexM_linear_df
)

### outer join input region
all_multi_cohorts <- Reduce(
  function(x,y, ...) merge(x, y, by = "cpg", all = TRUE, ...),
  cohort_ls
)
dim(all_multi_cohorts)
```

## for female

```{R}
cohort_ls <- list(
  Gasparoni = gasparoni_female_stage_linear_df,
  London = london_female_stage_linear_df,
  MtSinai = mtsinai_female_stage_linear_df,
  ROSMAP = rosmap_female_stage_linear_df
)

### outer join input region
female_multi_cohorts <- Reduce(
  function(x,y, ...) merge(x, y, by = "cpg", all = TRUE, ...),
  cohort_ls
)
dim(female_multi_cohorts)
```

## for male

```{R}
cohort_ls <- list(
  Gasparoni = gasparoni_male_stage_linear_df,
  London = london_male_stage_linear_df,
  MtSinai = mtsinai_male_stage_linear_df,
  ROSMAP = rosmap_male_stage_linear_df
)

### outer join input region
male_multi_cohorts <- Reduce(
  function(x,y, ...) merge(x, y, by = "cpg", all = TRUE, ...),
  cohort_ls
)
dim(male_multi_cohorts)
```

# Meta analysis

```{R, message = FALSE, warning = FALSE, results = 'hide'}
library(meta)
```

## Create a function for meta analysis

```{R}
metaAnalysis <- function(data, parallel = FALSE,
                         estimate = "Estimate", std = "StdErr"){
  meta_df <- plyr::adply(
    .data = data, .margins = 1, .fun =  function(rowOne_df){
      
      est <- rowOne_df[grep(estimate, colnames(rowOne_df))] %>% as.numeric
      
      direction <-  paste(
        ifelse(is.na(est), ".", ifelse(est > 0, "+", "-")), collapse = "")
      
      se <- rowOne_df[grep(std, colnames(rowOne_df))] %>% as.numeric
      
      cohort <- gsub(paste0("_", std),"",grep(std,colnames(rowOne_df),value = T))
      
      rowOne_reform_df <- data.frame(
        cohort = cohort,
        est = est,
        se = se,
        stringsAsFactors = FALSE)
      
      f <- metagen(
        TE = est,
        seTE = se,
        data = rowOne_reform_df)
      
      tibble::tibble(
        cpg = rowOne_df$cpg,
        estimate = f$TE.fixed,
        se = f$seTE.fixed,
        pVal.fixed = f$pval.fixed,
        pVal.random = f$pval.random,
        pValQ = f$pval.Q,
        direction = direction)},
    
    .progress = "time",
    .parallel = parallel,
    .id = NULL)
  
  ### create final pVal
  meta_df$pVal.final <- ifelse(
    meta_df$pValQ > 0.05, meta_df$pVal.fixed, meta_df$pVal.random)

  ### calculate fdr
  meta_df$fdr <- p.adjust(meta_df$pVal.final, method = "fdr")

  ### order meta_df
  meta_final_df <- meta_df[
    , c(grep("_",colnames(meta_df),invert = T),
        grep("_",colnames(meta_df),invert = F))]

  meta_final_df[order(meta_final_df$pVal.final),]}
```

## for all

```{R, eval = FALSE}
# doParallel::registerDoParallel(cores = parallel::detectCores()/2)
all_meta_df <- metaAnalysis(
  data = all_multi_cohorts, parallel = FALSE,
  estimate = "Estimate", std = "StdErr")
row.names(all_meta_df) <- NULL
```

## for female

```{R, eval = FALSE}
# doParallel::registerDoParallel(cores = parallel::detectCores()/2)
female_meta_df <- metaAnalysis(
  data = female_multi_cohorts, parallel = FALSE,
  estimate = "Estimate", std = "StdErr")
row.names(female_meta_df) <- NULL
```

## for male

```{R, eval = FALSE}
# doParallel::registerDoParallel(cores = parallel::detectCores()/2)
male_meta_df <- metaAnalysis(
  data = male_multi_cohorts, parallel = FALSE,
  estimate = "Estimate", std = "StdErr")
row.names(male_meta_df) <- NULL
```

```{R, include = FALSE, eval = FALSE}
save(
  all_meta_df,
  female_meta_df,
  male_meta_df,
  file = paste0(data.dir, "/single_meta.rda"))
```

# Add annotation

```{R, message = FALSE, warning = FALSE, results = 'hide'}
library(sesame)
library(rGREAT)
library(dplyr)
```

```{R, include = FALSE}
load(paste0(data.dir, "/single_meta.rda"))
```

## Call in annotation datasets

### Find probe postion on chromosomes

```{R}
probes.info <- sesameDataGet("HM450.hg19.manifest") %>% as.data.frame()

probes.info <- probes.info[, c("seqnames", "start", "end")]
colnames(probes.info)[1] <- "chr"
probes.info$chr <- as.character(probes.info$chr)
```

### Call in dataset with UCSC annotation

```{R}
UCSC_annot <- readRDS(paste0(data.annot, "/full.annot.rds"))

UCSC_annot <- UCSC_annot[
  , c("ILMNID", "UCSC_REFGENE_GROUP", "UCSC_REFGENE_ACCESSION",
      "UCSC_REFGENE_NAME", "RELATION_TO_UCSC_CPG_ISLAND")]
colnames(UCSC_annot) <- c(
  "cpg", "UCSC_RefGene_Group", "UCSC_RefGene_Accession",
  "UCSC_RefGene_Name", "Relation_to_Island")

UCSC_annot$cpg <- as.character(UCSC_annot$cpg)
UCSC_annot$UCSC_RefGene_Group <- as.character(UCSC_annot$UCSC_RefGene_Group)
UCSC_annot$UCSC_RefGene_Accession <- as.character(UCSC_annot$UCSC_RefGene_Accession)
UCSC_annot$UCSC_RefGene_Name <- as.character(UCSC_annot$UCSC_RefGene_Name)
UCSC_annot$Relation_to_Island <- as.character(UCSC_annot$Relation_to_Island)
```

## Create a function to add annotation into dataset

```{R}
annotateCpG <- function(data){
  
  ### add chrom and position
  dat <- merge(
    probes.info, data, by.x = "row.names", by.y = "cpg", sort = FALSE)
  colnames(dat)[1] <- "cpg"
  dat$cpg <- as.character(dat$cpg)
  
  ### add UCSC annotation
  dat <- merge(UCSC_annot, dat, by = "cpg", sort = FALSE)
  
  dat[
    ,c("cpg", "chr", "start", "end",
       colnames(dat)[
         grep("cpg|chr|start|end",
              colnames(dat), invert = T)])
  ]
}
```

## for all

```{R, eval = FALSE}
all_meta_annot_df <- annotateCpG(data = all_meta_df)
write.csv(
  all_meta_annot_df,
  paste0(data.dir, "/single_all_meta_annot.csv"),
  row.names = FALSE)
```

## for female

```{R, eval = FALSE}
female_meta_annot_df <- annotateCpG(data = female_meta_df)
write.csv(
  female_meta_annot_df,
  paste0(data.dir, "/single_female_meta_annot.csv"),
  row.names = FALSE)
```

## for male

```{R, eval = FALSE}
male_meta_annot_df <- annotateCpG(data = male_meta_df)
write.csv(
  male_meta_annot_df,
  paste0(data.dir, "/single_male_meta_annot.csv"),
  row.names = FALSE)
```

# Prepare datasets for comb-p

```{R, include = FALSE}
all_meta_annot_df <- read.csv(paste0(data.dir, "/single_all_meta_annot.csv"))
female_meta_annot_df <- read.csv(paste0(data.dir, "/single_female_meta_annot.csv"))
male_meta_annot_df <- read.csv(paste0(data.dir, "/single_male_meta_annot.csv"))
```

## for all

```{R}
all_meta_combp_df <- all_meta_annot_df[
  , c("chr", "start", "end", "pVal.final")
]
colnames(all_meta_combp_df)[4] <- "pValue"
write.csv(
  all_meta_combp_df,
  paste0(data.dir, "/single_all_meta_for_combp.csv"),
  row.names = FALSE)
```

## for female

```{R}
female_meta_combp_df <- female_meta_annot_df[
  , c("chr", "start", "end", "pVal.final")
]
colnames(female_meta_combp_df)[4] <- "pValue"
write.csv(
  female_meta_combp_df,
  paste0(data.dir, "/single_female_meta_for_combp.csv"),
  row.names = FALSE)
```

## for male

```{R}
male_meta_combp_df <- male_meta_annot_df[
  , c("chr", "start", "end", "pVal.final")
]
colnames(male_meta_combp_df)[4] <- "pValue"
write.csv(
  male_meta_combp_df,
  paste0(data.dir, "/single_male_meta_for_combp.csv"),
  row.names = FALSE)
```

# Compare results among male, female and interaction analysis

```{R, include = FALSE}
intxn_df <- read.csv(paste0(data.dir, "/single_all_meta_annot.csv"))
female_df <- read.csv(paste0(data.dir, "/single_female_meta_annot.csv"))
male_df <- read.csv(paste0(data.dir, "/single_male_meta_annot.csv"))
```

## data management

### select and rename needed variables for comparison

```{R}
intxn_df <- intxn_df %>%
  select(cpg, chr, start, end, UCSC_RefGene_Group, UCSC_RefGene_Accession,
         UCSC_RefGene_Name, Relation_to_Island, estimate, se, direction,
         pVal.final, fdr) %>%
  rename(intxn_est = estimate, intxn_se = se, intxn_direction = direction,
         intxn_pVal = pVal.final, intxn_fdr = fdr)

female_df <- female_df %>%
  select(cpg, estimate, se, direction, pVal.final, fdr) %>%
  rename(female_est = estimate, female_se = se, female_direction = direction,
         female_pVal = pVal.final, female_fdr = fdr)

male_df <- male_df %>%
  select(cpg, estimate, se, direction, pVal.final, fdr) %>%
  rename(male_est = estimate, male_se = se, male_direction = direction,
         male_pVal = pVal.final, male_fdr = fdr)
```

### combine datasets

```{R}
identical(intxn_df$cpg, female_df$cpg)
identical(female_df$cpg, male_df$cpg)

# because 3 datasets have identical cpgs, we can use cbind instead of merge here
dat_df <- cbind(intxn_df, female_df %>% select(-cpg), male_df %>% select(-cpg))
```

### create indicators for significant signals in each analysis

```{R}
dat_df$sig_intxn <- ifelse(dat_df$intxn_fdr < 0.05, 1, 0)
dat_df$sig_female <- ifelse(dat_df$female_fdr < 0.05, 1, 0)
dat_df$sig_male <- ifelse(dat_df$male_fdr < 0.05, 1, 0)
dat_df$sig_stratified <- ifelse(
  (dat_df$sig_female == 1 & dat_df$sig_male == 0) |
    (dat_df$sig_female == 0 & dat_df$sig_male == 1), 1, 0)
```

### select significant probes

```{R}
dat_sig_df <- dat_df %>%
  filter(sig_intxn == 1) %>%
  filter((sig_female == 1 & abs(female_est) > 0.02) |
           (sig_male == 1 & abs(male_est) > 0.02))
```

```{R, include = FALSE, eval = FALSE}
write.csv(dat_df, paste0(data.dir, "/compare_all_annot.csv"), row.names = FALSE)
write.csv(dat_sig_df, paste0(data.dir, "/compare_sig_annot.csv"), row.names = FALSE)
```

## Visualize results

```{R, include = FALSE}
dat_df <- read.csv(paste0(data.dir, "/compare_all_annot.csv"))
dat_sig_df <- read.csv(paste0(data.dir, "/compare_sig_annot.csv"))
```

### generate histograms

```{R, message = FALSE, warning = FALSE, results = 'hide'}
library(ggplot2)
```

```{R, warning = FALSE, message = FALSE}
female <- data.frame(
  abs_est = abs(dat_df$female_est),
  sex = "female",
  stringsAsFactors = F)

male <- data.frame(
  abs_est = abs(dat_df$male_est),
  sex = "male",
  stringsAsFactors = F)
plot_df <- rbind(female, male)

ggplot(plot_df, aes(abs_est, fill = sex)) +
  geom_histogram(alpha = 0.3,position="identity") +
  xlim(0,0.1) +
  labs(title = "Histogram of absolute estimates from meta analysis") +
  theme_bw()
```

```{R, warning = FALSE, message = FALSE}
female <- dat_df %>% filter(sig_female == 1)
female <- data.frame(
  abs_est = abs(female$female_est),
  sex = "female",
  stringsAsFactors = F)

male <- dat_df %>% filter(sig_male == 1)
male <- data.frame(
  abs_est = abs(male$male_est),
  sex = "male",
  stringsAsFactors = F)
plot_df <- rbind(female, male)

ggplot(plot_df, aes(abs_est, fill = sex)) +
  geom_histogram(alpha = 0.3,position="identity") +
  labs(title = "Histogram of absolute estimates for significant probes from meta analysis") +
  theme_bw()
```

```{R}
qqplot(dat_df$female_est, dat_df$male_est,
       main = "Q-Q plot of female estimates vs. male estimates",
       xlab = "quantiles of female estimates",
       ylab = "quantiles of male estimates")
abline(c(0,1))
```

```{R, warning = FALSE, message = FALSE}
female <- data.frame(
  est = dat_df$female_est,
  sex = "female",
  stringsAsFactors = F)

male <- data.frame(
  est = dat_df$male_est,
  sex = "male",
  stringsAsFactors = F)
plot_df <- rbind(female, male)

ggplot(plot_df, aes(est, fill = sex)) +
  geom_histogram(alpha = 0.3,position="identity") +
  xlim(-0.1, 0.1) +
  labs(title = "Histogram of estimates from meta analysis") +
  theme_bw()
```

```{R, warning = FALSE, message = FALSE}
female <- dat_df %>% filter(sig_female == 1)
female <- data.frame(
  est = female$female_est,
  sex = "female",
  stringsAsFactors = F)

male <- dat_df %>% filter(sig_male == 1)
male <- data.frame(
  est = male$male_est,
  sex = "male",
  stringsAsFactors = F)
plot_df <- rbind(female, male)

ggplot(plot_df, aes(est, fill = sex)) +
  geom_histogram(alpha = 0.3,position="identity") +
  labs(title = "Histogram of estimates for significant probes from meta analysis") +
  theme_bw()
```

### generate venn diagrams

```{R, message = FALSE, warning = FALSE, results = 'hide'}
library(GenomicRanges)
library(ChIPpeakAnno)
library(ggplot2)
```

```{R, warning = FALSE, message = FALSE}
sig_female_gr <- dat_df %>% filter(sig_female == 1) %>% makeGRangesFromDataFrame()
sig_male_gr <- dat_df %>% filter(sig_male == 1) %>% makeGRangesFromDataFrame()
sig_stratified_gr <- dat_df %>% filter(sig_stratified == 1) %>% makeGRangesFromDataFrame()
sig_intxn_gr <- dat_df %>% filter(sig_intxn == 1) %>% makeGRangesFromDataFrame()

### Venn 1
methodsLabel <- c("sig in sex stratified analysis", "sig in interaction analysis")

n <- length(methodsLabel)

gg_color_hue <- function(n){
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

cols = gg_color_hue(n)

ranges.list <- list(sig_stratified_gr, sig_intxn_gr)

makeVennDiagram(
  ranges.list,
  NameOfPeaks = methodsLabel[1:n],
  totalTest = 2000,
  by = "region",
  main = paste0(" "),
  col = c("#440154ff", "#21908dff"),
  fill = c(alpha("#440154ff",0.3), alpha("#21908dff",0.3)),
  cex = 1,
  fontfamily = "sans",
  cat.cex = 1,
  cat.default.pos = "outer",
  cat.pos = c(180, 180),
  cat.dist = c(-0.055, -0.055),
  cat.fontfamily = "sans",
  cat.col = c("#440154ff", "#21908dff"))

### Venn 2
methodsLabel <- c(
  "sig in female analysis", "sig in male analysis",
  "sig in sex stratified analysis", "sig in interaction analysis")

n <- length(methodsLabel)

gg_color_hue <- function(n){
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

cols = gg_color_hue(n)

ranges.list <- list(sig_female_gr, sig_male_gr, sig_stratified_gr, sig_intxn_gr)

# overlap for 1 repetition
makeVennDiagram(
  ranges.list,
  NameOfPeaks = methodsLabel[1:n],
  totalTest = 2000,
  by = "region",
  main = paste0(" "),
  col = c("#440154ff", "#21908dff", "#f9a242b2", "#ca0020"),
  fill = c(alpha("#440154ff",0.3), alpha("#21908dff",0.3), alpha("#f9a242b2",0.3), alpha("#ca0020",0.3)),
  cex = 1,
  fontfamily = "sans",
  cat.cex = 1,
  cat.default.pos = "outer",
  cat.pos = c(180, 180, 180, 180),
  cat.dist = c(-0.055, -0.055, -0.055, -0.055),
  cat.fontfamily = "sans",
  cat.col = c("#440154ff", "#21908dff", "#f9a242b2", "#ca0020"))
```

## Generate datasets to look into details

```{R}
dat <- read.csv(paste0(data.dir, "/compare_all_annot.csv"))
rbind1 <- read.csv(paste0(data.dir, "/single_all_meta_annot.csv"))
rbind2 <- read.csv(paste0(data.dir, "/single_female_meta_annot.csv"))
rbind3 <- read.csv(paste0(data.dir, "/single_male_meta_annot.csv"))
```

```{R}
cpg1 <- dat %>%
  filter((dat$sig_stratified == 1) & (dat$sig_intxn == 0) &
           (dat$sig_male == 1) & (dat$sig_female == 0)) %>%
  select(cpg) %>% unlist() %>% as.character()

cpg2 <- dat %>%
  filter((dat$sig_stratified == 1) & (dat$sig_intxn == 1) &
           (dat$sig_male == 1) & (dat$sig_female == 0)) %>%
  select(cpg) %>% unlist() %>% as.character()

cpg3 <- dat %>%
  filter((dat$sig_stratified == 1) & (dat$sig_intxn == 0) &
           (dat$sig_male == 0) & (dat$sig_female == 1)) %>%
  select(cpg) %>% unlist() %>% as.character()
```

```{R}
createDat <- function(cpg_chr){
  dat1 <- rbind1 %>% filter(cpg %in% cpg_chr) %>% mutate(data = "intxn")
  dat2 <- rbind2 %>% filter(cpg %in% cpg_chr) %>% mutate(data = "female")
  dat3 <- rbind3 %>% filter(cpg %in% cpg_chr) %>% mutate(data = "male")
  rbind(dat1, dat2, dat3)
}
```

```{R}
dat741_df <- createDat(cpg_chr = cpg1)
dat31_df <- createDat(cpg_chr = cpg2)
dat121_df <- createDat(cpg_chr = cpg3)
```

```{R, include = FALSE, eval = FALSE}
write.csv(dat741_df, paste0(data.dir, "/dat741_df.csv"), row.names = FALSE)
write.csv(dat31_df, paste0(data.dir, "/dat31_df.csv"), row.names = FALSE)
write.csv(dat121_df, paste0(data.dir, "/dat121_df.csv"), row.names = FALSE)
```
```